services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: helipagos_api
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      USE_DOCKER: "true"
    ports:
      - "3009:3009"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev

  postgres:
    image: postgres:16-alpine
    container_name: helipagos_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: helipagos_pgadmin
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin-servers.json:/pgadmin4/servers.json
      - ./docker/pgadmin/init-pgadmin.sh:/pgadmin4/init-pgadmin.sh
    command: ["/bin/sh", "/pgadmin4/init-pgadmin.sh"]

volumes:
  postgres_data:
  pgadmin_data:
